title: Nicholas Ritter
description: >-
  Metascience fellow at IFP. Writing at bayesian goldfish.
url: "https://nicholasritter.github.io"
substack_url: "https://bayesiangoldfish.substack.com"
github_username: nicholasritter

# Build settings
theme: minima
plugins:
  - jekyll-feed
